before_script:
  - sudo apt-get install libreoffice
  - sudo apt-get install imagemagick

language: node_js

node_js:
  - lts/*

install:
  - npm install

script:
  - npm run cover

# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
